const historicData = [
    {
        "id": "init_1",
        "name": "January 2025",
        "sortKey": 202501,
        "mode": "regular",
        "dictator": null,
        "globalPicks": { "game": "", "movie": "", "book": "" },
        "entries": {
            "Andrew": {
                "game": { "title": "Cat Quest 3", "imageUrl": "", "rating": "5", "thoughts": "Cat Quest 3 - turns out, its a kids game! I thought this got like IGN Game of the Year, so I figured it had to be good, and while it had polish, it didn't sink its claws into me. I found the difficulty way too easy, and could beat most bosses on my first try without even breaking a sweat." },
                "movie": { "title": "Hit Man", "imageUrl": "", "rating": "7", "thoughts": "I had heard 2024 was the year that Glen Powell launched, but I really didn't know who he was other than a one-time SNL guest host before watching this. He delivered, he was very funny and had a good range. In the movie you'll see him miraculously flipping from lame ass Gary to stud Ron the fake hitman. The lady interest in this is gorgeous and their chemistry is good. I didn't quite like the ending, which struck me as a little drastic, but I'd still recommend this as a fun watch with the wifey on a Saturday night." },
                "book": { "title": "Lock in (John Scalzi)", "imageUrl": "", "rating": "7", "thoughts": "Locked In (John Scalzi) - Good Scalzi book, moves at a quick pace. Thought he missed some opportunities to explore some of the more thought-provoking elements of his world where like 10% of people are vegetables that somehow have internet access and can download into droids. He is good at dialogues, and leans on that a lot. He does less exposition and I think at times that would have been nice to have more of." }
            },
            "Ross": {
                "game": { "title": "Stellar Blade", "imageUrl": "", "rating": "8", "thoughts": "Tots & Bots!!!! It's a shame Stellar Blade get so much shit for having a buxom protagonist because the underlying game is ROCK solid. It's probably 30-40 hours and the combat consistenly evolves over and over. For example, a perfect parry is good in its own right, then you get perfect parry + hold square for a counter, then you do parry / square / hold triangle and it's devastating. But the number of combos and how crunchy it feels is great. Story is meh but there's lots to do a la Ubisoft (there's even fishing). The boss fights are unique and the character designs are so freaking cool. Very beautiful graphics wise as well." },
                "movie": { "title": "Sonic 3", "imageUrl": "", "rating": "7", "thoughts": "Sonic 3 feels like the first movie that really nailed it out of all of them (Yes I've seen them, its half me and half Oliver). The cast is absolutely nuts with Idris Elba, Keanu Reeves, Jim Carrey, Cyclops from X-men, etc. There's fun little Sega references all through it and some heartwarming scenes about love & loss. Nothing particularly exciting from a plot perspective but it's a nice package and the fights are awesome - they're basically DBZ fights and Knuckles is hilarious" },
                "book": { "title": "The Mercy of Gods", "imageUrl": "", "rating": "9", "thoughts": "The expanse bois are BACK. It's impressive how quickly they can create a world & characters which you're invested in. A medium-length read with some fun philosophical stuff. There was the exploration of whether a free society or one ruled by a single party is best for managing chaos, all kinds of weird tech, and tons and tons of fun creatures to mess with. Utterly brutal in a few places and major characters die throughout. Excited to see what they bring for round 2" }
            },
            "Sean": {
                "game": { "title": "Armored Core 6", "imageUrl": "", "rating": "7", "thoughts": "Throwback to the OG Gundam robot combat games. A little grindy and repetitive, but the nostalgia is there for sho." },
                "movie": { "title": "Wicked", "imageUrl": "", "rating": "7", "thoughts": "Pretty good. A little-known Indy flick about some green lady and her blonde friend who can sing. Monkey birds also" },
                "book": { "title": "Empire of the Damned", "imageUrl": "", "rating": "8", "thoughts": "Second entry in a solid grimdark vampire saga. Action-packed, fantasy, with a great sense of humor. Highly recommend." }
            },
            "Tom": {
                "game": { "title": "Aliens Dark Descent", "imageUrl": "", "rating": "8", "thoughts": "Lots of tense fun. Story is so-so but they really capture the tension of Aliens, commanding a squad of marines down tight hallways and praying you dont stumble on a bunch of xenomorphs." },
                "movie": { "title": "Dark City", "imageUrl": "", "rating": "8", "thoughts": "Weird but great. Good late 90s trippy scifi, sort of a lesser known cousin of the Matrix. Great performances by Rufus Sewel, Kiefer Sutherland, and Jennifer Connelly. Sort of dated special effects but doesn't really matter. If you watch, mute the opening monologue bc it spoils the mystery." },
                "book": { "title": "The Last Honest Man", "imageUrl": "", "rating": "8", "thoughts": "Well-researched account of the Church Committee investigations and hearings in 1975, the first real attempt to force intelligence agencies to comply with laws. Lots of interesting characters and political tensions at play. Tragic central figure of Senator Frank Church, who was both a crusader for accountability and a showboater who wanted to run for president in 1976 but wasn't able to convert his committee sucess to campaign sucess." }
            }
        }
    },
    {
        "id": "init_2",
        "name": "February 2025",
        "sortKey": 202502,
        "mode": "regular",
        "dictator": null,
        "globalPicks": { "game": "", "movie": "", "book": "" },
        "entries": {
            "Andrew": {
                "game": { "title": "Hogwarts Legacy", "imageUrl": "", "rating": "9", "thoughts": "Masterfully realized hogwarts, great fundamentals of open world gameplay. Bravo" },
                "movie": { "title": "Nosferatu", "imageUrl": "", "rating": "7", "thoughts": "Sets a great creepy vibe, and even if the plot moves pretty slow, it was enjoyable." },
                "book": { "title": "Educated", "imageUrl": "", "rating": "10", "thoughts": "Freakin amazing story, hard to believe a person actually remembers all these episodes from her life, but what an interesting life she has led. Makes you thankful to have the parents you've got." }
            },
            "Ross": {
                "game": { "title": "Metaphor Refantazio", "imageUrl": "", "rating": "9", "thoughts": "This deserves a lot of the praise and GOTY awards it received, but it does fall short of a 10 I think. There's been a trend recently of Japanese creators getting involved with western fantasy (LOTR anime & Metaphor are two examples), and it's a cool fusion that seems unique. The premise of this game is that the King of the lands has been murdered, just after his son had been murdered by the same assailant. But when the King died, he set up some black magic to enforce a contest as to who should be next king, preventing his thrown from being usurped by the murderer. This would be chosen by the proportional thoughts of everyone in the kingdom at the end of a period of time, and anyone who tried to murder a candidate to be king would be in turn killed, so it really would be up to the people. Gameplay is equally compelling and stylish. It's turn-based combat, and any character can be any class. Likewise, as you develop different archetypes, you unlock new classes (so for instance Knight + Wizard must both be level 5 to unlock the Magic Knight), and you get to transfer over old moves as well to really be creative. Another cool tactic is that if you're powerful enough, you can active-battle enemies so that you don't even need to go into the turn-based screen. Outside of combat, you are in control of what you do (raise intelligence, strength, develop relationships, etc) but you can only do 1 thing per day and 1 thing per evening. The plot has some genuinely great twists and turns, and it's and interesting commentary on society (for instance, the king / prince murderer leads the election for most of the game, despite being brutally violent and shitty)." },
                "movie": { "title": "Captain America: Brave New World", "imageUrl": "", "rating": "1", "thoughts": "This is the single-handed worst fucking movie I have ever had the pleasure of watching. Not in a good way, fuck it was bad. I honestly can't understand how this could possibly have made it through Kevin Feige's filters. I don't even want to go on. Even by the rubric's standards, it's still a 1." },
                "book": { "title": "The Way of Kings (THE STORMLIGHT ARCHIVE)", "imageUrl": "", "rating": "10", "thoughts": "This is probably the fastest that I've ever devoured a 1200 page book. As I described to someone, this is a fantasy novel about a soldier / surgeon who carries bridges across giant chasms so that the military can race native tribesmen to murder giant crabs, whose hearts can provide super saiyan powers. There are a few subplots and flashbacks here and there, but for the most part it stays focused on the main characters which I really appreciate. The concept of some of the superpowers are so cool; one of the monks with powers inhales light which powers him, and he can lash objects to manipulate gravity. For instance, he'll lash a giant table to a wall far away, causing it to fall towards a wall and blow it up as he assassinate people. This is one book of 5, and supposedly they each get better. But the first book's events do such a good job at foreshadowing this sort of impending sense of doom that seems so much greater than the initial conflict, but there aren't stupid clickbaity-cliff hangers." }
            },
            "Sean": {
                "game": { "title": "Tunic", "imageUrl": "", "rating": "8", "thoughts": "Really unique plot progression and simple but satisfying gameplay. Really enjoyed the level of mystery early on combined with unlocking one of those oldschool booklet manuals as a form of progression. Cute fox with a sword. Dope." },
                "movie": { "title": "Ministry of Ungentlemanly Warfare", "imageUrl": "", "rating": "7", "thoughts": "Henry Cavil, Nazi Killing, general shenanigans, directed by Guy Ritchie. Really enjoyed this action comedy based on a true WWII covert mission by British intelligence. Would recommend." },
                "book": { "title": "Fury of the Gods", "imageUrl": "", "rating": "7", "thoughts": "Last pd John Gwynne's bloodsworn trilogy. Action packed and nicely tied up the trilogy. pace was a bit too fast, with more time needed on the final character arcs. Big ass wolf/dragons fights Also... the Hobitt. It was FINE TOM. Pretty good for a book nearly 90 years old, doesn't really measure up to current fantasy re: lack of immersive plot and landscapes. Dont know how they managed 3 extended version movies from this book, precious..." }
            },
            "Tom": {
                "game": { "title": "Warhammer 40k Rogue Trader", "imageUrl": "", "rating": "7", "thoughts": "Very crunchy CRPG set in the grim darkness of the 41st millenium where there is only war. Doesn't seem as polished as BG3 but it is fun to go really deep into the bonkers lore. Good characters and quests and exploration, but felt like they could have leaned more into the grimdark setting." },
                "movie": { "title": "Parasite", "imageUrl": "", "rating": "9", "thoughts": "See why this won so many awards. Really interesting exploration of class in modern Korean society. Liked very much how the poor family started off as the villians or parasites for the first half but by the second half became very clear the rich family were the evil parasites. Really well acted and intense." },
                "book": { "title": "Left Hand of Darkness", "imageUrl": "", "rating": "6", "thoughts": "Still got like 80 pages left, but interesting scifi novel exploration of gender. About an explorer who goes to a genetically modified planet of humans who only become male or female (and can switch) once a month for a few days. He tries to get them to open up relations with the rest of the human planets but struggles to navigate their society. Wish they had leaned more into how different they are, he often just uses male pronouns to talk to people currently in the neuter phase." }
            }
        }
    },
    {
        "id": "init_3",
        "name": "March 2025",
        "sortKey": 202503,
        "mode": "dictator",
        "dictator": "Andrew",
        "globalPicks": { "game": "Deeprock Galactic: Survivor", "movie": "Rashomon", "book": "Dungeon Crawler Carl" },
        "entries": {
            "Andrew": {
                "game": { "title": "", "imageUrl": "", "rating": "7", "thoughts": "Great game, good style and good times playing coop. Wouldn't play this without a friend, but with one it is quite funny. I liked the driller class, and felt the classes had a good variety between them, each giving something that made me want to play them or have them on my team. Enjoyed the level variety, surprised me with some of the parts like flying with rocket boots out of a giant drill shaft." },
                "movie": { "title": "", "imageUrl": "", "rating": "6", "thoughts": "Didn't get to watch it... blame India" },
                "book": { "title": "", "imageUrl": "", "rating": "8", "thoughts": "Liked it a lot, def easy to binge as you get invested in the character and curious about his upgrade path. I liked how the game rewards you for what you do, so he ends up being like a martial artist foot stomper. Starting with a regenerate tunic though is soooo unfair." }
            },
            "Ross": {
                "game": { "title": "", "imageUrl": "", "rating": "7", "thoughts": "Initially I had this game at a 6, but I upped it to a 7 because in the past year I have not laughed at hard in any life situation as I did at the dreaded blackout stout. I honestly was wheezing I was laughing so hard and to experience it with my boii was just super fun. Otherwise though, I didn't love it. It felt competently made, but the perk system was extremely useless, and the cosmetics were so few and far between. The core gameplay loop felt like it was good for 3-5 hours, but then it got stale and progress was super limited. They just need better progression and more impactful powers to really get this some place nice. TBD if it gets better after level 25 but I didn't have the impetus to do so." },
                "movie": { "title": "", "imageUrl": "", "rating": "5", "thoughts": "Rashomon....man. I really do enjoy a good mystery and for the time period it was released, I think a lot of it does hold up. Where it really falls apart for me is the dead guy's ghost coming out and giving a story. By that point in the movie I was just so over it. The pacing was atrocious and while it's probably a style, the bandit's cackle just got so old listening to over and over. Otherwise though, neat to see that common murder mystery plot points from this are still being used today, and it's a novel setting I haven't seen in a while. I don't think I'd recommend it to anyone to watch in 2025." },
                "book": { "title": "", "imageUrl": "", "rating": "7", "thoughts": "I really liked this book, but I feel like there are a few things keeping it from being an 8. A lot of the dialogue feels a little bit childish / Marvel-quippy when it needed a more serious tone or had more serious topics. Something that maybe shouldn't go against it, but I will judge it anyway, is that this is like a 15 book series. At the very least, Carl should've gotten through half of the dungeon or selected a class. I had a good time with it and it's a fun premise, but i'm not going back for more because I don't feel like the time-investment would pay off with how largely scoped it is." }
            },
            "Sean": {
                "game": { "title": "", "imageUrl": "", "rating": "7", "thoughts": "Fairly Fun all around. Blackout stout had by struggling to breate. Gameplay loop got stale fairly quickly. needed more mission diversity. level cap to progress the game far too high. Satisfying haptic feedback when hittin Dem rocks. pvp would have been a great addition" },
                "movie": { "title": "", "imageUrl": "", "rating": "6", "thoughts": "Soundtrack slaps! hHeeeEEEEYYH.... If I was a Japanese person in 1950: engaging camera work in the forest scenes, with some interesting perspectives, well composed shots. couldnt help but laugh at the medium channeling the dead guy. Laughing was on point for all actors. Fairly certain he ate that baby" },
                "book": { "title": "", "imageUrl": "", "rating": "7", "thoughts": "Enjoyed way more than expected. Unique and engaging concept from the start. Literary equivalent of a crunchy taco: fast, tasty, satisfying, bingeable." }
            },
            "Tom": {
                "game": { "title": "", "imageUrl": "", "rating": "6", "thoughts": "Fun gameplay loop but I think it was just not my cup of tea. Hard to feel the progression from loot from missions that make you more powerful. Seems similar I guess in some ways to Helldivers but I much prefer that. Fun anti-corporate bent though." },
                "movie": { "title": "", "imageUrl": "", "rating": "8", "thoughts": "Really enjoyed it. Rewatch from first seeing it like 15 years ago. Really groundbreaking way of telling a story. Kurosawa's direction is always impeccable too. Prefer some of Kurosawa's later stuff like Ran, but the theme of humans being unable to be honest when it comes to themselves is great." },
                "book": { "title": "", "imageUrl": "", "rating": "6", "thoughts": "Cute fun. Still have 150 pages to go. Sometimes the humor gets a little grating and reading a video game is less fun than playing one. Donut is cute tho." }
            }
        }
    },
    {
        "id": "init_4",
        "name": "April 2025",
        "sortKey": 202504,
        "mode": "regular",
        "dictator": null,
        "globalPicks": { "game": "", "movie": "", "book": "" },
        "entries": {
            "Andrew": {
                "game": { "title": "Grounded", "imageUrl": "", "rating": "10", "thoughts": "This game blew me away. Turns out, co-op with my wife in the survival/builder genre is a blast. She enjoyed building bases, while I went around fighting bugs and exploring dungeons. The difficulty is legit, and the spiders are SCARY at times. Really have to gear appropriately for the fight you're facing, which means you'll die a lot before you know what you're gonna face. The dungeons had great variety, and the finale was so hard we had to put it on easy. Loved that i could play a bit solo, keep my save game, host that multiplayer, and keep making progress." },
                "movie": { "title": "The Brutalist", "imageUrl": "", "rating": "6", "thoughts": "LONG AF. Dani liked it, and I can't say it was BAD, but it certainly doesn't really follow a proper story arc. Things just kind of happen, mostly shitty things. THe cinematography is good, and the performances are strong, which is what makes it more watchable than it otherwise would have been on the basis of its story. Turns out, NOT a true story at all, which was a surprise because it does seem pretty random to not be true." },
                "book": { "title": "Nexus: A Brief History of Information Networks from the Stone Age to AI", "imageUrl": "", "rating": "8", "thoughts": "Dude really has some thought provoking stuff about AI that makes you worry we're heading to an AI dystopia. Maybe we'll be like cats for AI overlords, not useful but not hated either. Chapters may run a bit long and sometimes sounds like the kind of deep stoner conversations people have in college, but the dude works in a lot of history to make his claims seem not so implausible. I recommend it if you're trying to get more worried about AI than you already are." }
            },
            "Ross": {
                "game": { "title": "Split Fiction", "imageUrl": "", "rating": "10", "thoughts": "Fuck, man, it was so good. I cannot overstate how amazing this game is to people who are interested in having fun with someone on the same couch. The premise is cool, the applications are cool, and every very puzzle feels meaningful for both players. THere was a period where I was running around as a piggy that could shit rainbows, and oliver could climb walls (via some foul mechanism). We ran through the level, just crusiing, and at some point fell into a meat grinder where we IMMEDIATELY turned into playable sausages. We played rhythm games, boat games, we slayed dragons, and most of all the final level was batshit fuckign insane. The actual split in the split screen started rotating, collapsing, and growing, to change everyone's perspective. The pinball level also blew my mind." },
                "movie": { "title": "Sinners", "imageUrl": "", "rating": "8", "thoughts": "I liked this movie a lot. And while it wasn't perfect, it was super refreshing as a new IP which is so rare these days. We had 3 independent hooks - 1.) Michael B. Jordan plays twins, 2.) It was a racism period piece, and 3.) it was a fucking vampire movie??? Haley Steinfeld slayed so hard. The transition from Period piece to outlandish vampire movie was handled IMMACULATELY and it even had a post credits scene which seems fucking ridiculous. The humor was sparsely but well played throughout the movie to break up the tension, and I just had a great time." },
                "book": { "title": "Words of Radiance", "imageUrl": "", "rating": "10", "thoughts": "Book 2 of the Way of Kings saga. 10/10, widely regarded as his best work. If the super saiyan warriors in medieval armor fighting crabs weren't enough, they add new characters with distinct powers like being able to draw illusions which come to life, as well as expand outside the original canyon location.  The book opens up to the entire universe while writing some of the best action scenes I have seen in a book to date. No notes, 10/10. I also finished his next short novel, which was not as good, but it's all in the spirit of assembling the team." }
            },
            "Sean": {
                "game": { "title": "High on Life", "imageUrl": "", "rating": "5", "thoughts": "Game had the humor element down for sure, intergalatic FPS bounty hunter with that classic rick and morty vibe you've grown to love. More than a bit repetitive gameplay loop. Admittedly only got throught the first 1-2 bounties, but might have potential. Talking guns, agressive talking knives, utterly ridiculous and hillarious dialogue." },
                "movie": { "title": "Sinners", "imageUrl": "", "rating": "8", "thoughts": "Really enjoyed this one. Not sure if this is a horror comedy or I just have a sick sense of humor. Double michael B, editing/CGI done really well, intriguing and believable vamper element, solid blues musical vibes that tied to a past/future plotline. Even though Ross missed most of the post-credit scene, it really tied the room toghether in the end. Would watch again." },
                "book": { "title": "The Kind Worth Killing", "imageUrl": "", "rating": "7", "thoughts": "Been kicking around my TBR for quite a while, glad to finally read. Well-paced and engaging thriller: MUERDER, scandal, and few great twists. Really well done shifts in perspective and timelines without being gimmicky or annoying. Perfect palate cleanser" }
            },
            "Tom": {
                "game": { "title": "God of War Ragnarok", "imageUrl": "", "rating": "8", "thoughts": "Great  combat, story isn't as good as the first. Incredible explorartion. Does drag a bit but a lot of fun. Voice acting is incredible and the interpretation of Norse mythology is so much fun." },
                "movie": { "title": "No Other Land", "imageUrl": "", "rating": "9", "thoughts": "Incrediblly bleak look at the Israeli occupation in the West Bank. The daily indignities plus pure cruetly make the West Bank seem far worse than Jim Crow South. Depressing as fuck but incredible." },
                "book": { "title": "Claudius the God", "imageUrl": "", "rating": "8", "thoughts": "Reviewing the whole two part series. Still got 100 pages left, but fascinating how much real history it's based off. Imperial family just murdered the fuck out of each other until the crippled nerd was the only one left and he ruled very competently. A bit slow at times and you need a family tree to reference but great historical fiction." }
            }
        }
    },
    {
        "id": "init_5",
        "name": "May 2025",
        "sortKey": 202505,
        "mode": "regular",
        "dictator": null,
        "globalPicks": { "game": "", "movie": "", "book": "" },
        "entries": {
            "Andrew": {
                "game": { "title": "Enshrouded", "imageUrl": "", "rating": "9", "thoughts": "Another BANGER. The building system is nuts, inspiring me to build stuff all over and explore to unlock new building materials and decorations. The voxel system works well for giving fine tooth control while still making it easy to build large and fast. Dani and I played this in co-op which was great fun. At one point a friend grabbed the game and the three of us ran through a dungeon which was epicly long and creepy. Very great lighting and graphics even if the animations arent so stellar. Combat is not so developed, but the environments are wonderful and really encourage exploration. Love the hand-made world and how you can find hidden chests behind hidden walls in hidden cellars. Really happy with this one and feel like this is developing my creativity." },
                "movie": { "title": "Wicked", "imageUrl": "", "rating": "7", "thoughts": "very solid! loved the songs and Ariana's physical comedy" },
                "book": { "title": "American War", "imageUrl": "", "rating": "7", "thoughts": "Very unlikable protagonist, but that was knd of the point! You're following around someone who is basically a terrorist and radical as fuck in her loyalty to the south which appears to have no moral stance other than an opposition to electrifying automobiles. Thought the book did a good job of moving with the character across her life to see how she ended up so fucked up. Not a feel good story. Interesting alternate future with a rising middle-eastern democratic superpower (although not a big part of the story)." }
            },
            "Ross": {
                "game": { "title": "Clair Obscur: Expedetion 33", "imageUrl": "", "rating": "10", "thoughts": "This game is an 11. Literally every last piece of it is a masterpiece. It's a jeRPG only in the fact that it's turn-based, otherwise very French. The soundtrack is something I listen to almost daily, the art style is stunning, and the plot is so fascinating. It's centered around grief and sadness losing loved ones. The combat system is astounding and you have to earnestly counter & dodge but has levels to it which make it extremely fun to learn" },
                "movie": { "title": "How to train your dragon 2", "imageUrl": "", "rating": "7", "thoughts": "I had never seen these movies but I really like them! The animation is a little stale in 2025, but it's really endearing. The sequel is better than the first (imo) in that the dergons are now established as friends of the humans, and it's more of a good vs evil story. Giant dragons fighting each other vs a hilarious puppy-like dawg who comes of age" },
                "book": { "title": "With the old blood", "imageUrl": "", "rating": "9", "thoughts": "Really well told book through the eyes of a soldier during the Pacific campaign of World War 2. It's tough to find a soldier from the trenches who isn't fucked in the head or poor at writing, but he finds a nice balance. It's literally otherworldy and unimaginable (like a dude carrying a grenade crate while strafing behind a tank, being shot at by a machine gun). It makes you grateful for the world we live in and the efforts of our forefathers" }
            },
            "Sean": {
                "game": { "title": "Split Fiction", "imageUrl": "", "rating": "8", "thoughts": "Man, totally blown away by the variety of gameplay and cooperative creativity. Love the rainbow farting pigs that get turned into sausage, by far my favoite plotline. Prolly go as high as 8/10 once finished!" },
                "movie": { "title": "Heretic", "imageUrl": "", "rating": "7", "thoughts": "A24 Film.Interesting plot - horrow/suspense with an interesting debate on religion. Specifically, recycling of western religion across human history and the underlying motives of control. Hugh grant definitely saved the move with some stellar acting. Things kind of fell apart halfway through, could have been 8/10 with some more thoughtful writing to close out an interesting premise." },
                "book": { "title": "Pillars of the Earth", "imageUrl": "", "rating": "7", "thoughts": "Heard great things about the book so pulled the trigger. Captivating character development set in the middle ages. Centered around the building of a cathedral which doesnt sound too interesting, but the writing and raw medieval setting keep you hooked. Dark, Bleak, hopeless at times but drives attachment to characters/villians as the story progresses. Great momentum through the first half, but quite a slog for the last 500 pages." }
            },
            "Tom": {
                "game": { "title": "Split Fiction", "imageUrl": "", "rating": "8", "thoughts": "Very fun. Only halfway through, which counts as a full completion with Sean. Lots of fun co op. Gameplay is varied and doesn't get stale. I wanna see these bitches make out though. Will probably go to a 9 once done. Playing through with the gf too and it's fun to see her enjoy a viggy game." },
                "movie": { "title": "Friendship", "imageUrl": "", "rating": "9", "thoughts": "A24 hilarious cringefest. Feels almost like a horror movie. Tim Robinson is amazing as usual as a complete weirdo. He acts like a character in his show whereas everyone else is normal. Paul Rudd is great. Some of the hardest laughs I've ever had in a movie theater." },
                "book": { "title": "Original Sin", "imageUrl": "", "rating": "7", "thoughts": "Writing isn't great, typical airport politics book. And Tapper is a bottom feeder who didn't report on this when it actually mattered. But the reporting is very good. So many people in the party knew what was going on for years and hoped they could keep the wool over everyone's eyes. Insane political malpractice. Biden is a completely senile Shakespearean protagonist in it. No mention of Gaza and how that impacted youth turnout. Still have 60 pages to go,  Biden is right on the edge of dropping out where I am in the book currently, mid-July." }
            }
        }
    },
    {
        "id": "init_6",
        "name": "June 2025",
        "sortKey": 202506,
        "mode": "dictator",
        "dictator": "Andrew",
        "globalPicks": { "game": "V Rising (PC)", "movie": "The Wild Robot", "book": "The Fifth Season (N.K. Jemisin)" },
        "entries": {
            "Andrew": {
                "game": { "title": "", "imageUrl": "", "rating": "8", "thoughts": "This cements my love for the survival crafting genre. This one wasn't so stereotypical because of the isometric view, whereas with grounded and enshrouded I was more used to a third person or first person view. I enjoyed this one a lot, thought they really nailed the vampire theme with things like sucking blood, hunting at night, dwelling in a coffin in a giant gothic castle, etc.  I did NOT like a few things: Durability (why is this even in games? dying was enough of a punishment in itself since you had to run back for your shit.) Anything that kept me from teleporting.. I turned off default game settings when I set this server up so that we could teleport more easily, but in the base rules of the game you cant teleport with like.. an iron ingot in your hands or a gemstone. What was this about? I am guessing something to do with PvP balancing, but where I felt the sting of teleportation rules was when it came to dropping off servants in my castle. I guess I should have moved my castle, but my castle in the starter area was nowhere near where the good minions were, so if I grabbed one I had to bring it all the way back to my castle on foot. It didn't feel good to build a castle and be told to move it either, like, recollect all the resources I already invested? No way!   I DID like the variety of weapons and how they invited diferent playstyles. The simplified magic system where verything just works on cooldowns and you pick three spells . Good progression when you kill bosses, they always seem to give something to get excited about. Would have liked to have played this with my boys but it was a tough month for me moving around the world." },
                "movie": { "title": "", "imageUrl": "", "rating": "6", "thoughts": "Liked it, mostly for the art style. Very painterly and impressionistic, which was just beautiful to look at. Try pausing it in any scene and just look at all the paint strokes! Wish there were video games with this kind of art style, maybe one of the cell shaded older prince of persia games? Plot was fine, the main robot seemed both all powerful and also kind of stupid at the same time, like it had no protocols for what to do in case of being stranded, so it just devoted its life to the duck? I did tear up a bit when the duck flew for the first time (goose?). Not sure the solution of having everyone in the same warm cabin and then asking them to play nice is feasible, predators gotta predate!" },
                "book": { "title": "", "imageUrl": "", "rating": "7", "thoughts": "Interesting world the author created, with society so focused on periodic apocolypses. Wouldn't be too hard to convince this public of the threat of climate change! I like what the author did with the protagonists and how they develop. What is the deal with there never being and 7, 8, or 9 ringers, only like 6s and below, and then a random 10 ringer guy so far ahead ofeveryone else. I am curious about the sequels but never really delve too deep into multi-book series for some reason. I think it is a little strange only one type of magic exists and not others. Also was unclear to me at what state of development the world was in, sometimes the author mentions electricity being a thing, and like turbines. I liked the 'wokeness' of it all, how there was like an unconventional menage-a-trois for a while. Sexual mores in this world are very different than in ours, but that always felt like a very background thing here, not thrown in our faces just sort of unremarkably a thing, which I appreciated." }
            },
            "Ross": {
                "game": { "title": "", "imageUrl": "", "rating": "8", "thoughts": "Really dug V Rising, I was woefully underprepared for how difficult it was going to be. I fully expected a bunch of survival crafting, but did NOT expect to need lightning fast reflexes and skill management to get through a lot of the bosses. The Horse knight, Spider Queen, Holy Angel, and Dracula populated my nightmares with how hard they were. It feels like a game really intended for co-op but I'm happy I was able to solo it. A few things that stood in the way of it being great: Weapon Durability was extremely poorly thought out. With such a hard difficulty curve, you literally had to use 95% of the same materials to repair items; it should've been severely reduced. I ended up just making new weapons and giving the damaged ones to my servants. Additionally, there were a few places where it was really obscure and hard to figure out what to do, but that was rare. Finally the Sun mechanic. Obnoxious as shit and always continued to be. Overall though, fantastic game, really enjoyed my ~50 hours with it and the Dracula fight was fantastic." },
                "movie": { "title": "", "imageUrl": "", "rating": "7", "thoughts": "Totallly serviceable, perfect \"7\" movie to me. The highlight for me was the absolutely stunning art style, and I also liked the messages it told about the unintended consequences of your parents raising you. The duckling acting like a robot everywhere and being rejected for being weird was sad but definitely caused a little of my own self-relection. Plot was wholly predictable, but it's a kids movie so I wasn't looking for that much. Oliver and I are going to be reading the 2nd book in the series soon and I'm looking forward to it." },
                "book": { "title": "", "imageUrl": "", "rating": "4", "thoughts": "I really did not like this book. There's a few things that really annoy me in books, and made up curses words are one of them. RUSTING EARTH just sounded so corny and stupid and it was like every other line. On top of that, 2nd person for the Essun sections really felt meaningless to me; just being weird to be weird and try and deceive from the real twist. It felt extremely juvenile towards the end becoming a threesome romance novel, and it was like AI generated how depressing can we get? ChatGPT please add more depression. The world was pretty cool and the powers were neat, the twist was something not many books do, so that's about where my appreciation ends. I'm totally open to this being just not suited to my personal tastes as GoodReads reviews were largely positive, but I just have no idea how this could be a Hugo Award winner, and would not recommend this to anyone." }
            },
            "Sean": {
                "game": { "title": "", "imageUrl": "", "rating": "7", "thoughts": "Thoroughly enjoyed V Rising on my first playthrough. Satifying progression system paired with expansive crafting and prompted exploration. Couldn't quite get it's hooks in me the second time around, but a great game! Enjoyed Ross having to refill my derelict castle with blood." },
                "movie": { "title": "", "imageUrl": "", "rating": "6", "thoughts": "I mean, you had me at baby animated otters. Cheerful plot with nice themes for a younger audience. Nice play across characters and evil AI corporation. Enjoyed the emotional moments of robot & wildlife bonding. Could have been a bit more brief in runtime." },
                "book": { "title": "", "imageUrl": "", "rating": "4", "thoughts": "Interesting pemise, but fairly poorly deployed. Not a fan of the initial first person third person narration with sparse world building. The manipulation of earthly elements via orogenes was an interesting premise, however would have enjoyed more in-depth plot on the actual training process/regimens. Somehat predictable twists that were not at all surprises. Would have enjoyed learning more about the rock-eaters, moon, etc. Aware this is a series, but felt cut short at the end. Needed more man on man threesome scenes." }
            },
            "Tom": {
                "game": { "title": "", "imageUrl": "", "rating": "9", "thoughts": "I really liked it. I've still got two final bosses, but having never really played a survival crafting, got much more into it than I thought I would. Loved collecting and categorizing and perfecting everything. But damn some of the end game bosses just feel so insanely difficult." },
                "movie": { "title": "", "imageUrl": "", "rating": "8", "thoughts": "Really cute. Watched it with Emma and we liked the animals and the animation style. Funny jokes about the very literal robot interacting with the animals." },
                "book": { "title": "", "imageUrl": "", "rating": "6", "thoughts": "Interesting world. I like the three stories all being different points in the protagonist's life but saw it coming. The romance scenes were a little high school fan fictiony. I liked the fact that it was far future from now and disaster focused as well as the magic system. Would have been cool to hear more about the Guardians and where their power comes from but that's probably in later books. But got pretty bored by the end." }
            }
        }
    },
    {
        "id": "init_7",
        "name": "July 2025",
        "sortKey": 202507,
        "mode": "regular",
        "dictator": null,
        "globalPicks": { "game": "", "movie": "", "book": "" },
        "entries": {
            "Andrew": {
                "game": { "title": "Cobalt Core", "imageUrl": "", "rating": "7", "thoughts": "I have been crushing this roguelike spaceship deckbuilder on steamdeck and enjoying it, a very good time passer. I get sucked into the just one more run of it each time I boot it up and end up playing at least two runs. It isn't so difficult, at least on normal difficulty, but I enjoy the different ways the various ships play and how good the decks get. I think the artifacts get sort of predictable as you go on, with some clearly being better than others, but they're still always fun to get." },
                "movie": { "title": "Mickey 17", "imageUrl": "", "rating": "6", "thoughts": "Funny to hear a protagonist with such a whiney, snivveling voice. I thought the movie was pretty entertaining, but it skewed in favor of telling a funny story rather than doing some mind-bending sci-fi stuff. Don't expect any sort of sixth sense like twist at the end here. The leader of their ship was so trumpian it was hilarious to see, the actor was really enjoying hamming that part up. The snow creatures were cute and gross as the same time, which was an impressive feat." },
                "book": { "title": "Bad Mexicans", "imageUrl": "", "rating": "8", "thoughts": "Pretty cool true story about a few of the Mexican revolutionaries (leftists and anarchists) who started planting the seeds for the overthrow of the dictator Porfirio Diaz who ruled for like 35 years in Mexico until 1910. These bad hombres didn't have much in the way of resources but somehow ran a print shop in Texas and St. Louis constantly evading U.S. authorities and somehow getting their publication distributed in Mexico. The U.S. immigration system/border control was so different back then, basically all we cared about was keeping Chinese out, wihle Mexicans were seen as a pretty good source of cheap labor. Wild to see how committed these people have to be to go after a ruthless dictator who would pretty calmly order executions for anyone he caught. The USA got along decently with Diaz and helped him by deporting lots of these dissenters into Mexico where they'd get scooped up. As I prepare to go to mexico, it was interesting to jump back to this formative moment in Mexican history." }
            },
            "Ross": {
                "game": { "title": "Doom The Dark Ages", "imageUrl": "", "rating": "9", "thoughts": "Nothing bad to say about this game. Doom ROCKS and has always executed flawlessly in my opinion since Doom 2016. The one knock I have is the story, which is totally fucking abysmal, and I don't know why they bother. Probably hours of cutscenes (by far the most of Doom so far), and I literally skipped them after the 2nd chapter. Otherwise, each game in the Doom trilogy has swapped core mechanics and this one is probably the 2nd best of the 3. This game is a little slower and turns you into a hulk-powered captain america (with a chainsaw-powered shield). The Shield parries projectiles and can bounce among people. When you jump from moderate heights you create earthquakes when you land, kibbling everyone near you. The guns are crunchy (one gun grinds skulls and shoots splinters) and the progression is SO satisfying. You have one gun like a needler where you pincushion enemies, and then throw the shield into them, and it explodes the splinters to do splash damage everywhere. I played on Nightmare, and it felt like the right challenge. I died a lot but it was fun trying to solve puzzles; one mechanic is kill the leader where you have to trash mobs until you kill enough of them. After that, the leader is vulnerable and you can kill them. So you pick and choose who to take out (ranged or melee people) and then go after the leader. There's also mounted-dragon missions and mech missions, and I just love Doom. Some of the smoothest, best single-player FPS campaigns out there." },
                "movie": { "title": "Fantastic Four", "imageUrl": "", "rating": "7", "thoughts": "Totally serviceable, didn't blow my mind but certainly a step up from the last like 6 years of marvel. Pedro & co di da nice job, good chemistry, and Galactus was a cool villain. Not entirely about like superpowers and stuff but more being a family. I enjoyed it" },
                "book": { "title": "The Sequel", "imageUrl": "", "rating": "5", "thoughts": "This is the sequel to \"The Plot,\" which really blew my mind, and is one of my most recommended books. Sad to say The Sequel really disappointed. I'd say about 65% of the plot rehashes core threads of The Plot, and my eyes kind of glazed over just going back through it all; it was no new information whatsoever. The protagonist is an antihero and extremely unlikable, which I don't usually vibe with, and that continued here. I was super curious about what would happen to them though, and for the parts that were novel, they were well executed and believable. I think the ending was really strong, it just seems like the author didn't have an entire book's worth of material. Maybe they should have just kept this to a novella or something." }
            },
            "Sean": {
                "game": { "title": "Vampire Survivor", "imageUrl": "", "rating": "7", "thoughts": "Pure Dopamine. Think endless vampire shooter survival with an addictive gameplay loop. Simple graphics but engaging concept that keeps you hooked. Only $4.99 for wasting hours of your time!" },
                "movie": { "title": "Phoenician Scheme", "imageUrl": "", "rating": "7", "thoughts": "Latest Wes Anderson Flick. Business Tycoon Benicio Del Toro assembles a farfetched scheme to conquer the coprorate world? Star studded cast with some really great cinematography. The plot was all over the place and subracted from the overall rating. Fast-paced, funny, hand grenades. Michael Cerra's character was amazing." },
                "book": { "title": "King of Ashes", "imageUrl": "", "rating": "5", "thoughts": "S.A. Cosby's latest novel (author of Blacktop Wasteland / Razorblade Tears). Intersting premise with quality plotlines on finding succes, returning to your hometown, family dynamic, and how the gangsta life intercedes with business." }
            },
            "Tom": {
                "game": { "title": "Return of the Obra Dinn", "imageUrl": "", "rating": "9", "thoughts": "Amazing mystery game. I would put as a 9.5, almost masterpiece. Best mystery game I've ever played. Great if you liked things like Master and Commander. Unfolds so organically and like actually hard mysteries that are solvable and you feel such a sense of accomplishment when you figure stuff out. Crazy that it was almost entirely made by one guy." },
                "movie": { "title": "Naked Gun", "imageUrl": "", "rating": "9", "thoughts": "Awesome old school slapstick. Liam Neeson is fantastic, does deadpan so well. Really rapid fire delivery. Directed by one of the guys from Lonely Island. Pamela Anderson was great too. I feel like this should be a sign to Hollywood to start making dumb fun slapstick comedies again." },
                "book": { "title": "Frankenstein", "imageUrl": "", "rating": "8", "thoughts": "Cool to read this classic. The pop culture image of this is way off. It's much more about how unbridled ambition and arrogance can destroy someone and everyone around them. Very 19th century British romantic language. It's also cool to see how she weaved in known science of the time to try to make it almost plausible. Also a lot of feminist undertones which is not something I would have originally assumed in this book. It becomes clear as the book goes on that Victor Frankenstein is the true monster because of how he behaved." }
            }
        }
    },
    {
        "id": "init_8",
        "name": "August 2025",
        "sortKey": 202508,
        "mode": "regular",
        "dictator": null,
        "globalPicks": { "game": "", "movie": "", "book": "" },
        "entries": {
            "Andrew": {
                "game": { "title": "Tactical Breach Wizards", "imageUrl": "", "rating": "8", "thoughts": "They nailed this game. Plays perfectly on a steam deck. Gameplay elements like being able to rewind are thematic as hell b/c one of the main characters has foresight of about 2 seconds into the future, so it is like you just lived what that character foresaw. This was extremely well written, with a great sense of humor. Fun bonus objectives on each level kept it difficult, although if you dont care about unlocking skins you can just cruise through it. The upgrades felt meaningful and powerful for each ability." },
                "movie": { "title": "KPop Demon Hunters", "imageUrl": "", "rating": "9", "thoughts": "Agree with Ross, great movie. Only thing that took it down to a 9 was how the other members of Huntrix \"forgave\" or \"accepted\" the main lady after her big reveal with literally NO DIALOGUES between them after the scene where they scorn her. Suddenly they are all ready to jam out with her the next time they see her." },
                "book": { "title": "The House on the Cerulean Sea", "imageUrl": "", "rating": "6", "thoughts": "Gays and birds" }
            },
            "Ross": {
                "game": { "title": "Death Stranding", "imageUrl": "", "rating": "7", "thoughts": "This is a weird fucking game that I definitely vibed well with. The gameplay was way more engaging than it had any right to be and it used the Horizon engine so it looked incredible. There was a really fun social aspect to building and connecting the world ; I would regularly take like a 45 minute journey, making ziplines along the way, and that journey would be cut down to 30 seconds afterwards for future missions. EXTREMELY SATISYING. The way that people  would \"like\" your things and you could see how they were used was also really cool. The characters were fire like most Kojoma games. \"Heart-man\" was this guy who lost his family by drowning in a lake so he kills himself over and over again on an attempt to talk to them in the after life, then after 3 minutes he resuscitates himself. Roaming through the world was super chill and the soundtrack was ace. I'd recommend it." },
                "movie": { "title": "KPop Demon Hunters", "imageUrl": "", "rating": "10", "thoughts": "Perfect 10; unless you really hate pop music, I don't see how everyone walks away with a positive experience here. Right out of the gate the characters are so endearing and literally every song is a banger. The emotions hit well with the protagonist and her journey, and the action scenes slap. Some of the best little animal sidekicks outside of Disney (Sussy & Derpy) and great humor. Shout-out to the corn on the cob looking abs. Taking the world by storm and deserves every bit of it." },
                "book": { "title": "Oathbringer (Stormlight Chronicles Book 3)", "imageUrl": "", "rating": "7", "thoughts": "3rd main book in the stormlight archive. This is the first book I've been a little down on, it feels like a slog of staging. The world building is still really fun though, it's so well thought out. Their version of hell / purgatory is really cool; anywhere that's land is a sea of marbles that are all stand ins for objects. The conflict is building and the setup is looking pretty good, but this took a while." }
            },
            "Sean": {
                "game": { "title": "Webfishing", "imageUrl": "", "rating": "4", "thoughts": "$5 Steam find. I'm a sucker for any fishing game. Literally any shape or form. Such a bizarre game. This is basically a grindy minimalist game. Pick your cat or dog skin, catch fish, level up gear, rinse and repeat. Chat with randos on the internet. Wasted about 8 hours of my life tryna catch em' all" },
                "movie": { "title": "Formula 1", "imageUrl": "", "rating": "7", "thoughts": "Brad Pit, Pod Racing, much humor. Solid racing movie, and satifying if you enjoyed watching the Netflix F1 series. Plot did a great job of keeping you off guard. Funny, Fast, Not furious. Writing kind of petered out a bit towards the end, felt a bit forced with the love interest, but wrapped things up nicely in the end." },
                "book": { "title": "The World According to Garp", "imageUrl": "", "rating": "8", "thoughts": "Re-read of a classic. Famous feminist writer knocks herself up via a dying pilot. Book is about her son, Garp. Floundering writer that navigates as a young husband and father. Long distance runner scenes and day to day life are full of energy! Something about the pace of writing is very engaging. Interesting blend of dark humor, absurdity, and deep characters that just works. Theres a scene where someone gets their dick bitten off. Highly recommend. Pretty solid Robin Williams movie adaptation." }
            },
            "Tom": {
                "game": { "title": "Kingdom Cum Deliverance II", "imageUrl": "", "rating": "8", "thoughts": "Really awesome game. Incredible world building. Feels lived in and small ball quests are so much fun and so refreshing in a RPG. Tutorials are bad though and not well explained so has a steep learning curve. But if you stick with it, story and characters and setting is great. Feels like the closest you can get to experiencing medieval life through a video game." },
                "movie": { "title": "Alien", "imageUrl": "", "rating": "10", "thoughts": "Saw it in college but had completely forgotten it and would always watch Aliens instead when I was in the mood. Went back and watched it. Absolute masterpiece. Especially in light of it being a standalone at the time without some big universe behind it. Everything feels so real and lived in. Characters are incredibly fleshed out and unique. Permeated with such dread. The last 30 minutes of the movie are a masterclass in pacing. Probably the best standalone scifi movie of its time. Aliens is awesome and I love it but I think Alien is a masterpiece." },
                "book": { "title": "Jurassic Park", "imageUrl": "", "rating": "6", "thoughts": "Movie is definitely better. There are some good bits that were cut from the book. Old Man Hammond is much more of a villian and there's a big anti-corporate streak that was kind of sanded out of the movie. But pacing in the book is not as good and characters can sometimes be more one dimensional in the book. Compys are fun and raptors are far scarier though." }
            }
        }
    },
    {
        "id": "init_9",
        "name": "September 2025",
        "sortKey": 202509,
        "mode": "dictator",
        "dictator": "Andrew",
        "globalPicks": { "game": "Pentiment", "movie": "The Lighthouse", "book": "The Proud Tower" },
        "entries": {
            "Andrew": {
                "game": { "title": "", "imageUrl": "", "rating": "5", "thoughts": "" },
                "movie": { "title": "", "imageUrl": "", "rating": "2", "thoughts": "" },
                "book": { "title": "", "imageUrl": "", "rating": "5", "thoughts": "" }
            },
            "Ross": {
                "game": { "title": "", "imageUrl": "", "rating": "5", "thoughts": "This game feels like a best picture nom; it's pretentious as hell and I don't know in what world it should be considered a 10, with a metacritic score of 86. Outside of the content (which we'll get to), there was just a lot of given that should've happened, with fast travel being the biggest omission. Menus were obtuse as hell for no conceivable reason and they were like dragged along instead of being crisp, arrows. I often just wouldn't even bother with quests or investigation clues because it would take me 2 minutes to find it in the menu. I was also annoyed that the text took SO long to scroll, when the game was solely about reading. I think the content here is quite good, and the best part about this game is going to be discussing it with the boiis to see who everyone accused. I suspect there's a LOT that some people will see and others won't see. I accused Fennec and Hannah. I caught Fennec doing all kinds of dark shit and magic, so he was a natural fit. I also did a few fun intuition things; I made the mother let me keep the book without destroying in the beginning, and I made \"Martin\" tell me his secret. I also found Hanna & The mill guy hooking up behind the sewers. There were fun things that I didn't know how the consequences would be; I found 2 friars fukkin in the library, and when I tried to \"run away,\" i broke my ankle. There were some pretty sad parts that I'm not sure needed to be there, just felt like they added the whole dead son thing in just to make him hate himself. I could take it or leave that. There was plenty of intrigue, and it wrapped up well, but it was just such a slog to play." },
                "movie": { "title": "", "imageUrl": "", "rating": "8", "thoughts": "The more I think about the lighthouse, the more i liked the lighthouse. The descent into madness is just so well done and so fun. I read that Rpatt and Willem dafoe didn't even stay together on set or talk to each other outside of scripting just to keep it real weird. The drunken dancing scene was absolutely hilarious \"YOU DON'T LIKE ME LOBSTAH??\" and the memes that have come out of it were awesome. I was pretty captivated the entire time seeing where it would go, and I thought it would be a lot more gross or weird but it was actually just a good story about madness. Can't wait to see the sequel." },
                "book": { "title": "", "imageUrl": "", "rating": "3", "thoughts": "Wowowowowowow. I thought I forgot how to read when I read chapter 1. It was so fucking scatter-brained and disengaging that every sentence I had to refocus myself. Despite its age, it was just shitty writing. You'd get 2 or 3 sentences about a person and then it would whiplash to someone else, like \"Should I know who this is? I've never even heard of this human.\" She would also spend quite a bit of time on people, and after you were hooked, just be like \"and then they fucked off, doesn't really matter what happened to them.\" One dude was like a guy of tremendous virtue and got sent off to Ireland during the IRA, and we just, never found out what happened to him. The assassination / anarchy section was pretty interesting, but it could've been told so much better. Cool to hear how it affected the entire globe (I was annoyed chapter 1 was basically ONLY the UK). Italians, Americans, unions, etc, all pretty neat. Sounds like everyone kind of capitulated and said \"well guess we need some kind of organization\" and so that movement died, but it was fun to hear about how it would affect a world even before the internet" }
            },
            "Sean": {
                "game": { "title": "", "imageUrl": "", "rating": "4", "thoughts": "Scripting sounds, ink, and stylization of text pretty satisfying during dialogue. Pacing really lost me in the second half. A bit frustrating not possible to fully investigate all suspects in act 1 (skill issue). Would have enjoyed a better match between the slow pace of exploration and ability to experience all plotlines." },
                "movie": { "title": "", "imageUrl": "", "rating": "7", "thoughts": "Why'd you spill yer beans, Tommy? I enjoyed this one. Surely bizarre at face value, yet captivating in its whack a doo plotline. Scenes of chugging honey-soaked turpentine and grinding seabirds into a thin paste had me chuckling. The erotic cosmic horror and mermaid vagine... icing on the cake. Bumped from a 6 to 7 after I savored the bloody chamberbot themes. I bet Dafoe and Pattinson had a blast filming.  Prometheus reimagined?" },
                "book": { "title": "", "imageUrl": "", "rating": "3", "thoughts": "Prologue slaps, if only the same level of actual entertainment could have been carried through. NGL first chapter has been a struggle to get into. This was denser than a physics or biochemistry textbook, without even a hint of narrative control or reader engagement. Chapter 1 -- fan-DU-Syeh-kleh - expansion of technology & prosperity vs. the growing disparity of upper and working classes - expansion of nationlism and setting up treaties for... some interesting parallels to be drawn vs. current day - AI and the consolidation of wealth and power. Chapter 2 - Anarchism and violence, not something that's even remotely organized in the current day... everyone's too limped dick these days to buck the established authority. Get it together Tom. Intensification of surveillance rings true, along with media portrayal of left of right/center ideology. Highlighted a need to balance government/state control and individual freedoms. A more perfect union?" }
            },
            "Tom": {
                "game": { "title": "", "imageUrl": "", "rating": "6", "thoughts": "Interesting really in depth take on early modern Europe. Can see the tension between the old medieval world and the Renaissance starting. Art and writing was very cool. But pacing in the last act really dragged on. Took a while to come together on the theme of what matters, truth or what people want to believe in truth. Some frustrating and repetitive mechanics. But can really tell it was a labor of love. All in all very unique and glad I played it, but maybe could have been a bit shorter." },
                "movie": { "title": "", "imageUrl": "", "rating": "8", "thoughts": "I really loved it. Seeing those two act across from each other was wild. The historical attention to detail was wild, accents, and everything. The descent into madness was compelling to watch. Seems like it was a labor of love by all involved. Mix of Edgar Allen Poe, Lovecraft, homoeroticism, plus greek mythology." },
                "book": { "title": "", "imageUrl": "", "rating": "4", "thoughts": "Damn Chapter 1 was a slog. I feel like the author is assuming so much knowledge of these guys, that maybe was more common in the 60s when written. Chapter 2 was a lot more interesting and seemed to set up a lot of the threads that eventually led to the Russian Revolution. I read Chapter 3 about America and it was actually pretty interesting. Might make myself finish the book. She does paint a picture but man it's just such a slog and I feel like I was missing out on the important historical parts" }
            }
        }
    },
    {
        "id": "init_10",
        "name": "October 2025",
        "sortKey": 202510,
        "mode": "regular",
        "dictator": null,
        "globalPicks": { "game": "", "movie": "", "book": "" },
        "entries": {
            "Andrew": {
                "game": { "title": "Borderlands 4", "imageUrl": "", "rating": "8", "thoughts": "Exactly what I wanted from Borderlands. I liked the movement upgrades, the lasso pull thingy and the mantling and climbing worked pretty well. Double jump and slam were nice although I didn't use slam a lot." },
                "movie": { "title": "28 Years Later", "imageUrl": "", "rating": "8", "thoughts": "" },
                "book": { "title": "Tomorrow, Tomorrow, and Tomorrow", "imageUrl": "", "rating": "10", "thoughts": "Beautifully written and engaging story focused in on two friends who have a love for eachother that is complicated but precious. Sometimes Sadie is a bit of a B. Plot moves forward nicely at a good clip. Thought it was written in a way that was very plain to read, which I appreciated a lot." }
            },
            "Ross": {
                "game": { "title": "Hades 2", "imageUrl": "", "rating": "9", "thoughts": "Return to shadow!!! This game paralyzed me. I was fully planning to play Borderlands 4, Ghost of Yotei, FFX, and more, but none of that happened. It's a common occurence when Hades is involved and I should've known better. The power curve is almost perfectly tuned; you really struggle continuously across both the underworld and the surface but always make just a LITTLE more progress. Runs are perfect around 38 minutes (which drops to like 24 after you power up) and the challenges and spins are so fun. I got the platinum, and I'm glad I did. It really forced me to try every last aspect and combination of powers, as well as see all the relationships. Content wise, it felt great. I think the whole experience took me 50ish hours to get through it all. Some of the permutations of builds are just hilarious - I had one where it was \"Only take 1 damage for the next hit,\" and also \"Previous boons duration is extended for 2 more boss fights\" so I only took 1 damage for 2 entire worlds. It's so fun seeing what you can create. I think Hades 1 was a perfect 10 without question, but Hades 2 had some struggles for the follow-up, which makes me put it at a 9. The characters are less engaging this time around because they had to pull from the fringes of the pantheon, and the ending was quite bad (to the point they're literally patching it, requiring 3 more runs of story and dialogue). I also thought the weapons were quite a bit less engaging and throughtful than the first one; the final aspects were strong and hilariously overpowered, but the ones in between were typically pretty meh." },
                "movie": { "title": "One Battle After Another", "imageUrl": "", "rating": "9", "thoughts": "This movie was phenomenal. I don't know a lot about Paul Thomas Anderson, but sounds like he has finally created something that is widely loved by critics and audience alike. Leo is an amazing paranoid dad and revolutionary bomber. Sean Penn is also insanely unhinged with an absolutely hilarious gait and really leans into the \"Creepy pervert\". The action is basically nonstop and the kills are fun and creative. It was basically 3 hours and I had no problems with the pacing. Even after the central plot was resolved, there was still another 15-20 minutes but it ended well and that's pretty tough to do. I had a blast with this" },
                "book": { "title": "Ararat", "imageUrl": "", "rating": "7", "thoughts": "This was a fun junk food horror book with a fun little premise. \"Ararat\" is a mountain in Turkey which is widely considered to hold Noah's Ark in real life (or where it likely ended up). The book takes this on a spin and has a volcano erupt nearby, blowing a hole in Ararat and revealing the ark. When researchers race to be the first to get there, really bad shit starts happening when it gets occupied. There's some fun interesting things about secular Turks vs religious christians and how the ark should be treated, and tons of gory massacres. Everybody decides to get the fuck out of there and people are still dying all the way down the mountain. A couple nice little twists and turns with redirects, and a nice little cliffhanger at the end. There's apparently a sequel where the same people involved discover pandora's box in Egypt, but I don't think I'll go there unless I need some more junk food." }
            },
            "Sean": {
                "game": { "title": "Kindgom Come Deliverance II", "imageUrl": "", "rating": "8", "thoughts": "Just complete medieval immersion. Really got sucked into this one. Excellent crafting, combat, and stealth systems. Satifying lockpicking mechanics with extensive and varying dialogue outcomes. Enjoyed getting yelled at by NPCs for being dirty or having a shitty horse. Combat system was frustrating at first but super satisfying after learning the master strike system. Background dialogues between NPCs is often hillarious." },
                "movie": { "title": "Weapons", "imageUrl": "", "rating": "7", "thoughts": "Totally unique horror concept. 17 kids go missing overnight, all from the same class, except for one. Stars RUTH LANGMORE and Josh Brolin. Multiple overlapping perspectives, done quite well to keep you guessing as the mysery unfolds." },
                "book": { "title": "The Devils", "imageUrl": "", "rating": "7", "thoughts": "Another solid novel by Abercrombie. Blends grimdark, medieval fantasy, and comedic elements well. A company of misfits including a werewolf, vampire, necromancer, and elf set out to place a homeless girl on the trone of Troy... hijinks ensure. Really great perspectives from the werewolf; manages to keep a hillarous tone and banter throughout. Solid combat scenes as you'd expected from Abercrombie." }
            },
            "Tom": {
                "game": { "title": "Tactical Breach Wizards", "imageUrl": "", "rating": "8", "thoughts": "Really fun tactics game. Feels like more of a puzzle than a tactics game with all the wizards' different unique skills. Very fun story with snappy writing, really funny. Great 15 hour tactics game to play over a weekend." },
                "movie": { "title": "Warfare", "imageUrl": "", "rating": "8", "thoughts": "Very small focus, platoon of SEALS in 2006 in a house in Ramadi, Iraq. Feels very small scale and realistic. Made by the guys who were there. No broader picture of why they're there because in the moment it doesn't really matter.  Actors are great, directing is fantastic. Sort of anticlimatic which makes sense because it tries to mirror exactly what went down. No jingoistic anti-Iraqi stuff, they pretty much are just off on the roofs away." },
                "book": { "title": "Lies of Locke Lamora", "imageUrl": "", "rating": "7", "thoughts": "Pretty good but still have 100 pages left. Like a fantasy medieval Venice setting with a little bit of magic. Follows a gang of con-men as they try to swindle merchants and nobility but they get caught up in a bigger gang war. Will probably read the second one, three are out but it's supposed to be a 7 book series eventually. Don't think I'd read it the whole way through though. Fun to see how they pull the cons off." }
            }
        }
    },
    {
        "id": "init_11",
        "name": "November 2025",
        "sortKey": 202511,
        "mode": "regular",
        "dictator": null,
        "globalPicks": { "game": "", "movie": "", "book": "" },
        "entries": {
            "Andrew": {
                "game": { "title": "Arc Raiders", "imageUrl": "", "rating": "7", "thoughts": "Loot loot loot. Felt like I was playing loot simulator. I think the skill trees are very underdeveloped and never made me feel more powerful. More than anything, I appreciate that this is one of those rare non fps games that got the crew together for regular multiplayer sessions. I'd like to see better progressin and less grind." },
                "movie": { "title": "Como agua para chocolate", "imageUrl": "", "rating": "7", "thoughts": "What a wild movie, back in the 90s, movies could have so much nudity! Sad to see the protagonist choose to go after her emotionally abusive heartthrob instead of the DOPE as hell american. Suprrised they wrote the american guy in such a nice way, very much a gentleman. I would have thought another Mexican would have been fair to write in the story. Interesting how it is set during hte mexican revolution and helped cement some of my historical knowledge. The food looked pretty tasty." },
                "book": { "title": "Chip Wars", "imageUrl": "", "rating": "6", "thoughts": "Good overview of how some of the biggest companies around today (NVIDIA anyone?) came to be and the breakthroughs in silicon valley that led to the entire digital era. Didn't go quite as much into the more modern world of AI and the datacenters springing up around the world that I wanted it to, but I think it was published a few years ago so that makes sense. This made me really appreciate the critical role Taiwan plays in the global economy and how that is both a problem for the United States AND for China and possibly makes the world a lot safer since even China doesn't want to invade if it risks destroying the world's source of advanced semiconductors." }
            },
            "Ross": {
                "game": { "title": "Ghost of Yotei", "imageUrl": "", "rating": "6", "thoughts": "Ghost of Yotei, ugh. I wanted to like this so much more than I did, and I think that Sucker Punch just got way too egotistical after the reception of the first game from Japan. It is SO pretentious and it annoys the ever living shit out of me. They think that everything they crafted is so good that you can't even skip like side quest dialogue in an OPEN WORLD GAME. On top of that, the gameplay really did not change that dramatically; I mean this in the example of it feels so PS4; you're still helping people up ledges, squeezing through cracks, transitioning with camera angles and none of that shit should happen in a ps5 exclusive. I wonder if they wanted to shoehorn it in. Otherwise, the story is just a standard Japanese revenge story and the character has an emotional resonance of a stone. Combat is TOP notch though, and the outfits and world are absolutely stunning. I had a blast whenever I got into combat scenarios and it felt so fluid and fun. The number of tools you had at your disposal were insane, and there was a nice nature element where you got a wolf, bird, and other animals to help you. The issue is that every 5 minutes you were interupted with another slow walking or 10 minute dialogue section. I hope for their next game they go back to electric infamous style play and ditch some of the realism so we can have some fun again." },
                "movie": { "title": "Frankenstein", "imageUrl": "", "rating": "7", "thoughts": "I wanted to love this movie more than I did, but I think the only cons really come down to pacing issues for me personally. The movie was about 2.5 hours, and about 30 minutes of it was Frankenstein hanging out on a farm in the woods with a family. It was super well acted and Guillermo del toro is kind of unmatched in the monster movie aesthetic. Frankenstein's powers were SO cool and it really portrayed how strong he was. It was bloody and tragic as hell. I think if they cut 15 minutes from the woods it would be a really exceptional movie. It just grinded everything to a halt." },
                "book": { "title": "The Crusades", "imageUrl": "", "rating": "9", "thoughts": "Really enjoyed this book, WAY more than I expected. A nonfiction 800pg rager of the history of the crusades. The first crusade, in particular, was really insane and the flip of a coin could probably have altered history fairly easily. Christians were starved and broken and one dumb decision ended up making them win; also someone find a lance literally buried in a cathedral and called it the holy lance, and that seemed to turn everything around. That dude got merked in the 2nd crusade though. There were also people flinging decapitated heads at their loved ones on trebuchets, and I read about a group called the Mamluks which I didn't read about before, but they were so viscious and successful they even repelled the mongols more than once. Huge fan." }
            },
            "Sean": {
                "game": { "title": "Arc Raiders", "imageUrl": "", "rating": "7", "thoughts": "Loot, Shoot, and Skoot. Really enjoying and got it's hooks in me straight away. Would like to see more evolution in base building, inventory management, and character skill trees. PVP element really sets this one apart. AS I WAS SAYING. First open chat experience with Ross had me dying for like 5 min. Almost an 8. Would like to see where they take this concept." },
                "movie": { "title": "The Substance", "imageUrl": "", "rating": "2", "thoughts": "Interesting concept with a sci-fi medical treatment that allows you to split your self into a younger, more attractive version. Demi Moore and Dennis Quaid couldn't save this one. The ending was so drawn out and bizarre, truly tanked the whole film. Could have been an hour shorter." },
                "book": { "title": "Anthropocene Reviewed", "imageUrl": "", "rating": "7", "thoughts": "Interesting analysis of all the human event which embody the anthopocene. Human existence is distilled into events and rated out of 5 stars. Interesting premise of condensed facts, combined with inter-related stories about the human impact on the planet." }
            },
            "Tom": {
                "game": { "title": "Arc Raiders", "imageUrl": "", "rating": "8", "thoughts": "Really enjoying this one. Loving the feeling of the clock ticking down. PVP fuckers make it more tense but I really hate them. Good combat and maps." },
                "movie": { "title": "Eddington", "imageUrl": "", "rating": "9", "thoughts": "Incredible fever dream for what 2020 felt like. Captures the paranoia of that summer. Joaquin Phoenix and Pedro are great. Supporting characters are too. Shows how community fraying causes people to lose touch with what's real and fall down whatever rabbit hole is conveinient. Shows how a lot of the current insanity came from an inability to actually deal with the trauma of COVID and everything else.  And shows how like the little culture war fights are all a distraction." },
                "book": { "title": "Burr", "imageUrl": "", "rating": "8", "thoughts": "Interesting historical novel written mainly from Aaron Burr's perspective. Written in the 1970s after Watergate so the theme is kind of how our legends and heroes don't measure up in real life. Washington is portrayed as a dumbass who is only really good at making sure he stays on top, Jefferson is a hypocritical schemer, Hamilton as a sociopathic monarchist. Still have 120p to go but it's a lot of fun. I don't think it should necessarily be read as like the untold story, Burr is clearly an unreliable narrator. But lots of fun." }
            }
        }
    },
    {
        "id": "init_12",
        "name": "December 2025",
        "sortKey": 202512,
        "mode": "dictator",
        "dictator": "Andrew",
        "globalPicks": { "game": "Kunitsu-Gami: Path of the Goddess", "movie": "Ballerina", "book": "Mistborn: The Final Empire" },
        "entries": {
            "Andrew": {
                "game": { "title": "", "imageUrl": "", "rating": "7", "thoughts": "" },
                "movie": { "title": "", "imageUrl": "", "rating": "8", "thoughts": "" },
                "book": { "title": "", "imageUrl": "", "rating": "9", "thoughts": "" }
            },
            "Ross": {
                "game": { "title": "", "imageUrl": "", "rating": "9", "thoughts": "Really enjoyed this game, got the plat. Some of the NG+ challenges were really fun. Progression was fun and I'm glad it was short" },
                "movie": { "title": "", "imageUrl": "", "rating": "8", "thoughts": "3 really memorable scenes otherwise a solid Jon Wick movie" },
                "book": { "title": "", "imageUrl": "", "rating": "9", "thoughts": "Enjoyed it a lot. Metal system was super cool and the sanderlanche was amazing" }
            },
            "Sean": {
                "game": { "title": "", "imageUrl": "", "rating": "7", "thoughts": "Really interesting game design, which had me intrigured initially with the setup and art style. Kind of bounced off for a bit, and couldn't get back into it about halfway through the progression. Prolly finish soon." },
                "movie": { "title": "", "imageUrl": "", "rating": "6", "thoughts": "Halfway through - passable Jon Wick action flick" },
                "book": { "title": "", "imageUrl": "", "rating": "8", "thoughts": "Lies of Lock Lamora vibes in the early crew setup scenes. Interesting allomancy hard-magic system, that really evolves into an intriguing through line throughout. Interesting characters, that could have been a bit more realized. Great conclusion/twist with the Lord Ruler, and enjoyed the chapter fragments from the perspective of the chosen one. Seeing where the powers evolve will keep me reading the series." }
            },
            "Tom": {
                "game": { "title": "", "imageUrl": "", "rating": "7", "thoughts": "8===D~~~" },
                "movie": { "title": "", "imageUrl": "", "rating": "6", "thoughts": "8===D~~~" },
                "book": { "title": "", "imageUrl": "", "rating": "", "thoughts": "8===D~~~" }
            }
        }
    }
];

// If local storage is empty, inject historic data
if (!localStorage.getItem('mediaTrackerState')) {
    localStorage.setItem('mediaTrackerState', JSON.stringify({
        months: historicData,
        currentMonthId: "init_12", // Default to the latest month
        viewMode: "month"
    }));
}
